"""initial schema

Revision ID: 56154208ca2d
Revises: 
Create Date: 2026-08-14 23:34:53.324723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '56154208ca2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_about',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', name='content_status_enum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('content_agents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('tools_raw', sa.Text(), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', name='content_status_enum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_agents_name'), 'content_agents', ['name'], unique=True)
    op.create_index(op.f('ix_content_agents_slug'), 'content_agents', ['slug'], unique=True)
    op.create_table('content_commands',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('argument_hint', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', name='content_status_enum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_commands_slug'), 'content_commands', ['slug'], unique=True)
    op.create_table('content_knowledge',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metadata_type', sa.Enum('user', 'feedback', 'project', 'reference', name='memory_type_enum'), nullable=False),
    sa.Column('folder_team', sa.Enum('engineering', 'product', 'qa', 'docs', name='team_enum'), nullable=False),
    sa.Column('metadata_team', sa.Enum('engineering', 'product', 'qa', 'docs', name='team_enum'), nullable=False),
    sa.Column('effective_team', sa.Enum('engineering', 'product', 'qa', 'docs', name='team_enum'), nullable=False),
    sa.Column('team_mismatch', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', name='content_status_enum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_knowledge_effective_team'), 'content_knowledge', ['effective_team'], unique=False)
    op.create_index(op.f('ix_content_knowledge_name'), 'content_knowledge', ['name'], unique=True)
    op.create_table('content_skills',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', name='content_status_enum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_skills_name'), 'content_skills', ['name'], unique=True)
    op.create_index(op.f('ix_content_skills_slug'), 'content_skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team', sa.Enum('engineering', 'product', 'qa', 'docs', name='team_enum'), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='role_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_table('invocation_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('persona_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persona_model', sa.String(), nullable=False),
    sa.Column('persona_system_prompt', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('repo_branch', sa.String(), nullable=True),
    sa.Column('container_id', sa.String(), nullable=True),
    sa.Column('container_status', sa.Enum('provisioning', 'cloning', 'ready', 'running', 'idle', 'error', 'terminated', name='container_status_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', 'error', 'timed_out', 'limit_reached', name='session_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idle_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('wall_clock_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['content_agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='sync_run_status_enum'), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('source_commit_sha', sa.String(), nullable=True),
    sa.Column('counts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_limits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_sessions_per_day', sa.Integer(), nullable=False),
    sa.Column('max_tokens_per_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role_enum'), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'tool_use', 'tool_result', name='message_content_type_enum'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_use_id', sa.String(), nullable=True),
    sa.Column('tool_result_content', sa.Text(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['invocation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('sync_run_flags',
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Enum('team_mismatch', 'parse_error', 'other', name='sync_flag_type_enum'), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.Enum('agent', 'skill', 'command', 'knowledge', 'about', name='sync_content_type_enum'), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_call_audit_log',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chat_message_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_excerpt', sa.Text(), nullable=True),
    sa.Column('stderr_excerpt', sa.Text(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['invocation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_audit_log_session_id'), 'tool_call_audit_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_call_audit_log_session_id'), table_name='tool_call_audit_log')
    op.drop_table('tool_call_audit_log')
    op.drop_table('sync_run_flags')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('user_limits')
    op.drop_table('sync_runs')
    op.drop_table('invocation_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_content_skills_slug'), table_name='content_skills')
    op.drop_index(op.f('ix_content_skills_name'), table_name='content_skills')
    op.drop_table('content_skills')
    op.drop_index(op.f('ix_content_knowledge_name'), table_name='content_knowledge')
    op.drop_index(op.f('ix_content_knowledge_effective_team'), table_name='content_knowledge')
    op.drop_table('content_knowledge')
    op.drop_index(op.f('ix_content_commands_slug'), table_name='content_commands')
    op.drop_table('content_commands')
    op.drop_index(op.f('ix_content_agents_slug'), table_name='content_agents')
    op.drop_index(op.f('ix_content_agents_name'), table_name='content_agents')
    op.drop_table('content_agents')
    op.drop_table('content_about')
    # ### end Alembic commands ###
